database:
  driver: postgres
  dsn: "postgres://shells:shells_password@localhost:5432/shells?sslmode=disable"
  max_connections: 25
  max_idle_conns: 5
  conn_max_lifetime: 1h

logger:
  level: info
  format: console

discovery:
  timeout: 30s
  max_depth: 3

security:
  rate_limit:
    requests_per_second: 10
    burst_size: 20
  enable_auth: true
  # API key will be loaded from SHELLS_API_KEY env var
