version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shells
      POSTGRES_USER: shells
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shells_dev_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shells"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check
      - "55679:55679" # zpages

  shells-api:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    command: ["serve", "--host", "0.0.0.0", "--port", "8080", "--config", "/app/config.yaml"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      WEBSCAN_REDIS_ADDR: redis:6379
      WEBSCAN_DATABASE_DRIVER: postgres
      WEBSCAN_DATABASE_DSN: "postgres://shells:${POSTGRES_PASSWORD:-shells_dev_password}@postgres:5432/shells?sslmode=disable"
      WEBSCAN_TELEMETRY_ENDPOINT: otel-collector:4317
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml
    restart: unless-stopped

  webscan-worker:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    command: ["worker", "--config", "/app/config.yaml"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
    environment:
      WEBSCAN_REDIS_ADDR: redis:6379
      WEBSCAN_DATABASE_DRIVER: postgres
      WEBSCAN_DATABASE_DSN: "postgres://shells:${POSTGRES_PASSWORD:-shells_dev_password}@postgres:5432/shells?sslmode=disable"
      WEBSCAN_TELEMETRY_ENDPOINT: otel-collector:4317
    volumes:
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 3
    restart: unless-stopped

  nmap:
    image: instrumentisto/nmap:latest
    network_mode: host
    command: ["tail", "-f", "/dev/null"]
    cap_add:
      - NET_ADMIN
      - NET_RAW

  zap:
    image: owasp/zap2docker-stable:latest
    ports:
      - "8090:8090"
    command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.key=webscan-api-key"]
    
volumes:
  postgres_data:
  redis_data: