# Bug Bounty Optimized Configuration for High-Value Vulnerabilities
# Focus: Auth Bypass, API Security, Business Logic, Request Smuggling, SSRF, Access Control

version: 1

# Core settings
database:
  driver: sqlite3
  dsn: shells-bounty.db

logger:
  level: info
  format: json

# Smart Attack Surface Discovery
# Maintains footprinting but prioritizes high-value targets
discovery:
  max_depth: 3
  max_assets: 5000
  timeout: 30m
  
  # Asset prioritization scoring
  asset_scoring:
    # High priority patterns (score 100)
    critical_patterns:
      - pattern: "*/login*"
        score: 100
        reason: "Authentication endpoint"
      - pattern: "*/auth*"
        score: 100
        reason: "Authentication endpoint"
      - pattern: "*/oauth*"
        score: 100
        reason: "OAuth endpoint"
      - pattern: "*/saml*"
        score: 100
        reason: "SAML endpoint"
      - pattern: "*/api/*"
        score: 90
        reason: "API endpoint"
      - pattern: "*/graphql*"
        score: 90
        reason: "GraphQL endpoint"
      - pattern: "*/admin*"
        score: 85
        reason: "Admin interface"
      - pattern: "*/payment*"
        score: 85
        reason: "Payment processing"
      - pattern: "*/checkout*"
        score: 85
        reason: "Payment processing"
      - pattern: "*/transfer*"
        score: 80
        reason: "Business logic"
      - pattern: "*/account*"
        score: 75
        reason: "Account management"
      - pattern: "*/profile*"
        score: 70
        reason: "User data access"
      - pattern: "*/upload*"
        score: 70
        reason: "File upload"
      - pattern: "*/download*"
        score: 65
        reason: "File access"
      - pattern: "*/webhook*"
        score: 65
        reason: "SSRF potential"
      - pattern: "*/callback*"
        score: 65
        reason: "SSRF potential"
      - pattern: "*/redirect*"
        score: 60
        reason: "Open redirect"
  
  # Smart discovery modules
  modules:
    # Keep footprinting but make it smarter
    passive_dns:
      enabled: true
      priority: 50
      focus_on_subdomains:
        - api
        - auth
        - login
        - admin
        - payment
        - oauth
        - sso
        - iam
        - identity
        - account
        - user
        - portal
        - dashboard
        - console
        - manage
        - secure
        - private
        - internal
        - dev
        - test
        - stage
        - uat
    
    certificate_transparency:
      enabled: true
      priority: 60
      filter_patterns:
        - "*api*"
        - "*auth*"
        - "*admin*"
        - "*portal*"
        - "*dashboard*"
        - "*console*"
        - "*internal*"
    
    port_scanning:
      enabled: true
      priority: 70
      smart_scan: true
      focus_ports:
        - 80    # HTTP
        - 443   # HTTPS
        - 8080  # Alternative HTTP
        - 8443  # Alternative HTTPS
        - 9200  # Elasticsearch (potential data exposure)
        - 6379  # Redis (potential session hijacking)
        - 3000  # Node.js apps
        - 8000  # Django/Python apps
        - 5000  # Flask apps
        - 4567  # Sinatra/Ruby
        - 9000  # PHP-FPM
        - 8888  # Jupyter (often misconfigured)
    
    web_crawling:
      enabled: true
      priority: 80
      smart_crawl: true
      prioritize_paths:
        - "/api"
        - "/v1"
        - "/v2"
        - "/graphql"
        - "/auth"
        - "/oauth"
        - "/saml"
        - "/login"
        - "/signin"
        - "/admin"
        - "/dashboard"
        - "/console"
        - "/account"
        - "/profile"
        - "/payment"
        - "/checkout"
        - "/cart"
        - "/order"
        - "/.well-known"
        - "/swagger"
        - "/api-docs"
        - "/openapi"
      
      # Look for these specific files
      interesting_files:
        - "/.git/config"
        - "/.env"
        - "/config.json"
        - "/package.json"
        - "/composer.json"
        - "/swagger.json"
        - "/openapi.json"
        - "/graphql/schema"
        - "/.well-known/openid-configuration"
        - "/.well-known/oauth-authorization-server"
        - "/robots.txt"
        - "/security.txt"
    
    technology_detection:
      enabled: true
      priority: 40
      identify:
        - authentication_frameworks
        - api_frameworks
        - payment_processors
        - session_management
        - cloud_services

# High-Value Vulnerability Scanners Configuration
scanners:
  # 1. Authentication Bypass - Highest Priority
  auth:
    enabled: true
    priority: 100
    modules:
      saml:
        golden_saml: true
        signature_bypass: true
        xml_injection: true
        assertion_manipulation: true
      
      oauth2:
        authorization_code_injection: true
        state_parameter_attacks: true
        redirect_uri_validation: true
        token_leakage: true
        jwt_attacks:
          algorithm_confusion: true
          none_algorithm: true
          key_confusion: true
          weak_secrets: true
          kid_injection: true
      
      jwt:
        algorithm_confusion: true
        signature_bypass: true
        key_injection: true
        claim_tampering: true
        expiration_bypass: true
      
      sso:
        account_takeover: true
        session_fixation: true
        relay_attacks: true
      
      multi_factor:
        bypass_techniques: true
        rate_limiting: true
        backup_codes: true
  
  # 2. API Security - Second Priority  
  api:
    enabled: true
    priority: 90
    modules:
      graphql:
        introspection: true
        query_depth_attack: true
        injection: true
        authorization_bypass: true
        information_disclosure: true
        batching_attacks: true
        
      rest:
        method_override: true
        authorization_bypass: true
        rate_limiting: true
        mass_assignment: true
        parameter_pollution: true
        version_disclosure: true
        
      general:
        api_key_disclosure: true
        endpoint_discovery: true
        swagger_misconfiguration: true
        cors_misconfiguration: true
        webhook_vulnerabilities: true
  
  # 3. Business Logic - Third Priority
  logic:
    enabled: true
    priority: 85
    modules:
      payment:
        price_manipulation: true
        currency_confusion: true
        race_conditions: true
        coupon_stacking: true
        negative_amounts: true
        
      account:
        privilege_escalation: true
        account_takeover: true
        registration_takeover: true
        password_reset_poisoning: true
        
      workflow:
        state_manipulation: true
        sequence_bypass: true
        time_based_attacks: true
        
      data_access:
        idor: true
        uuid_prediction: true
        parameter_tampering: true
        forced_browsing: true
  
  # 4. Request Smuggling - Fourth Priority
  smuggling:
    enabled: true
    priority: 80
    techniques:
      cl_te: true
      te_cl: true
      te_te: true
      http2_smuggling: true
    
    exploitation:
      cache_poisoning: true
      request_routing: true
      auth_bypass: true
      waf_bypass: true
    
    detection:
      differential_responses: true
      timing_attacks: true
      automated_fuzzing: true
  
  # 5. SSRF - Fifth Priority
  ssrf:
    enabled: true
    priority: 75
    modules:
      detection:
        url_parameters: true
        webhooks: true
        file_imports: true
        image_processing: true
        pdf_generation: true
        
      exploitation:
        internal_scanning: true
        cloud_metadata: true
        local_file_read: true
        service_interaction: true
        
      bypasses:
        url_encoding: true
        dns_rebinding: true
        redirect_chains: true
        protocol_smuggling: true
  
  # 6. Access Control - Sixth Priority
  access_control:
    enabled: true
    priority: 70
    modules:
      idor:
        automatic_detection: true
        uuid_testing: true
        incremental_ids: true
        parameter_manipulation: true
        
      authorization:
        horizontal_escalation: true
        vertical_escalation: true
        role_confusion: true
        jwt_role_manipulation: true
        
      data_exposure:
        direct_object_access: true
        api_filtering_bypass: true
        graphql_field_access: true
        mass_assignment: true

# Exploitation helpers
exploitation:
  # Automatic exploit generation
  auto_exploit: true
  
  # Proof of concept generation
  poc_generation:
    authentication_bypass: true
    api_authorization: true
    business_logic: true
    request_smuggling: true
    ssrf: true
    access_control: true
  
  # Impact demonstration
  impact_analysis:
    data_access: true
    privilege_escalation: true
    financial_impact: true
    account_takeover: true

# Smart Workflow Automation
workflows:
  # High-value target identification
  identify_critical_assets:
    - discover_authentication_endpoints
    - discover_api_endpoints
    - discover_payment_functionality
    - discover_admin_interfaces
    - identify_user_data_endpoints
  
  # Vulnerability discovery pipeline
  vulnerability_pipeline:
    - test_authentication_bypass
    - test_api_authorization
    - test_business_logic
    - test_request_smuggling
    - test_ssrf
    - test_access_control
  
  # Automatic escalation
  escalation_chain:
    - find_initial_vulnerability
    - escalate_privileges
    - demonstrate_impact
    - generate_report

# Reporting optimized for bug bounties
reporting:
  format: 
    - markdown
    - json
    - html
  
  severity_scoring:
    use_cvss: true
    use_bugcrowd_vrt: true
    
  auto_generate:
    executive_summary: true
    technical_details: true
    reproduction_steps: true
    impact_assessment: true
    remediation_advice: true
    
  evidence_collection:
    screenshots: true
    request_response: true
    video_poc: false  # Set to true if needed

# Performance and safety
performance:
  # Parallel scanning for efficiency
  parallel_workers: 10
  
  # But with safety limits
  rate_limiting:
    global_rps: 50
    per_host_rps: 10
    burst_size: 20
  
  # Smart scheduling
  scan_scheduling:
    prioritize_high_value: true
    defer_low_priority: true
    
# Integration with bug bounty platforms
integrations:
  platforms:
    hackerone:
      enabled: true
      import_scope: true
      
    bugcrowd:
      enabled: true
      import_scope: true
      
    intigriti:
      enabled: true
      import_scope: true
      
    yeswehack:
      enabled: true
      import_scope: true